### PR TITLE
add snippet from Sublime Text Snippet

### PR DESCRIPTION
**Pull request by exdeniz**
I' convert snippet from https://github.com/P233/Jade-Snippets-for-Sublime-Text-2 and include to package

### CODE REVIEW

**Comment by denysdovhan** [comment]
That is amazing! Please merge it! I'm waiting for this.

**Comment by LinusU** [comment]
Lets! :beers:

**Comment by LinusU** [comment]
Published as `0.6.0`!

**Comment by denysdovhan** [comment]
@LinusU dont forget update apm package! I want to do update just now.

**Comment by LinusU** [comment]
It's already done ;)

**Comment by denysdovhan** [comment]
@LinusU nice work! You're awesome! :+1:

**Comment by LinusU** [comment]
Thanks :+1:

**Comment by denysdovhan** [comment]
Hey @LinusU look at #55 here.

**Comment by LinusU** [comment]
Ouch :(

**Pull request merged**
