### PR TITLE
Fix atom 1.0 deprecations

### PR DESCRIPTION
**Pull request by ArnaudRinquin**
Just renamed `scoped-properties` directory to `settings`

### CODE REVIEW

**Comment by detj** [comment]
@devongovett I also sent another PR for this exact thing. Please delete if you wish to. I should have checked existing Pull Requests first.

**Comment by LinusU** [comment]
This fixes #30 #32 #36 #39 #41 #42

**Comment by detj** [comment]
Thanks :+1:

**Comment by devongovett** [comment]
Hey guys, sorry about the wait. I don't have much time to maintain this package anymore, and I don't use Atom anymore either. If any of you are interested in maintaining this package, please let me know and I'll transfer it to you.

**Comment by LinusU** [comment]
I use Atom daily and could certainly take it upon myself to test, merge and release pull requests.

**Comment by devongovett** [comment]
Awesome, thanks! I've added you as a collaborator to the repo. You should also be able to publish using [apm](https://github.com/atom/apm) as a result.

**Comment by LinusU** [comment]
Nice, thanks! :beers:

**Pull request merged**
